// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: apps/product-rpc/product.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductRpc_CreateProduct_FullMethodName    = "/product.ProductRpc/CreateProduct"
	ProductRpc_GetProduct_FullMethodName       = "/product.ProductRpc/GetProduct"
	ProductRpc_ListProducts_FullMethodName     = "/product.ProductRpc/ListProducts"
	ProductRpc_SetProductStatus_FullMethodName = "/product.ProductRpc/SetProductStatus"
)

// ProductRpcClient is the client API for ProductRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductRpcClient interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	SetProductStatus(ctx context.Context, in *SetProductStatusRequest, opts ...grpc.CallOption) (*SetProductStatusResponse, error)
}

type productRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewProductRpcClient(cc grpc.ClientConnInterface) ProductRpcClient {
	return &productRpcClient{cc}
}

func (c *productRpcClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, ProductRpc_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, ProductRpc_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, ProductRpc_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) SetProductStatus(ctx context.Context, in *SetProductStatusRequest, opts ...grpc.CallOption) (*SetProductStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetProductStatusResponse)
	err := c.cc.Invoke(ctx, ProductRpc_SetProductStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductRpcServer is the server API for ProductRpc service.
// All implementations must embed UnimplementedProductRpcServer
// for forward compatibility.
type ProductRpcServer interface {
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	SetProductStatus(context.Context, *SetProductStatusRequest) (*SetProductStatusResponse, error)
	mustEmbedUnimplementedProductRpcServer()
}

// UnimplementedProductRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductRpcServer struct{}

func (UnimplementedProductRpcServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductRpcServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductRpcServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductRpcServer) SetProductStatus(context.Context, *SetProductStatusRequest) (*SetProductStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProductStatus not implemented")
}
func (UnimplementedProductRpcServer) mustEmbedUnimplementedProductRpcServer() {}
func (UnimplementedProductRpcServer) testEmbeddedByValue()                    {}

// UnsafeProductRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductRpcServer will
// result in compilation errors.
type UnsafeProductRpcServer interface {
	mustEmbedUnimplementedProductRpcServer()
}

func RegisterProductRpcServer(s grpc.ServiceRegistrar, srv ProductRpcServer) {
	// If the following call panics, it indicates UnimplementedProductRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductRpc_ServiceDesc, srv)
}

func _ProductRpc_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_SetProductStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProductStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).SetProductStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_SetProductStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).SetProductStatus(ctx, req.(*SetProductStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductRpc_ServiceDesc is the grpc.ServiceDesc for ProductRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductRpc",
	HandlerType: (*ProductRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductRpc_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductRpc_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductRpc_ListProducts_Handler,
		},
		{
			MethodName: "SetProductStatus",
			Handler:    _ProductRpc_SetProductStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/product-rpc/product.proto",
}
