// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userrpc

import (
	"context"

	"go-svc/apps/user-rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetByKratosIdentityRequest          = user.GetByKratosIdentityRequest
	GetByKratosIdentityResponse         = user.GetByKratosIdentityResponse
	GetOrCreateByKratosIdentityRequest  = user.GetOrCreateByKratosIdentityRequest
	GetOrCreateByKratosIdentityResponse = user.GetOrCreateByKratosIdentityResponse
	GetUserRequest                      = user.GetUserRequest
	GetUserResponse                     = user.GetUserResponse

	UserRpc interface {
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		// Phase 9: Kratos identity ↔ local user mapping.
		GetOrCreateByKratosIdentity(ctx context.Context, in *GetOrCreateByKratosIdentityRequest, opts ...grpc.CallOption) (*GetOrCreateByKratosIdentityResponse, error)
		GetByKratosIdentity(ctx context.Context, in *GetByKratosIdentityRequest, opts ...grpc.CallOption) (*GetByKratosIdentityResponse, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// Phase 9: Kratos identity ↔ local user mapping.
func (m *defaultUserRpc) GetOrCreateByKratosIdentity(ctx context.Context, in *GetOrCreateByKratosIdentityRequest, opts ...grpc.CallOption) (*GetOrCreateByKratosIdentityResponse, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetOrCreateByKratosIdentity(ctx, in, opts...)
}

func (m *defaultUserRpc) GetByKratosIdentity(ctx context.Context, in *GetByKratosIdentityRequest, opts ...grpc.CallOption) (*GetByKratosIdentityResponse, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetByKratosIdentity(ctx, in, opts...)
}
