---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: go-svc
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: go_svc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: go-svc
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: go-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: postgres-secret
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "go_svc"]
            initialDelaySeconds: 2
            periodSeconds: 2
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "go_svc"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
