// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package orderrpc

import (
	"context"

	"go-svc/apps/order-rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderRequest     = order.CreateOrderRequest
	CreateOrderResponse    = order.CreateOrderResponse
	GetOrderRequest        = order.GetOrderRequest
	GetOrderResponse       = order.GetOrderResponse
	ListUserOrdersRequest  = order.ListUserOrdersRequest
	ListUserOrdersResponse = order.ListUserOrdersResponse

	OrderRpc interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
		ListUserOrders(ctx context.Context, in *ListUserOrdersRequest, opts ...grpc.CallOption) (*ListUserOrdersResponse, error)
	}

	defaultOrderRpc struct {
		cli zrpc.Client
	}
)

func NewOrderRpc(cli zrpc.Client) OrderRpc {
	return &defaultOrderRpc{
		cli: cli,
	}
}

func (m *defaultOrderRpc) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderRpcClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	client := order.NewOrderRpcClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) ListUserOrders(ctx context.Context, in *ListUserOrdersRequest, opts ...grpc.CallOption) (*ListUserOrdersResponse, error) {
	client := order.NewOrderRpcClient(m.cli.Conn())
	return client.ListUserOrders(ctx, in, opts...)
}
