// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: inventory.proto

package server

import (
	"context"

	"go-svc/apps/inventory-rpc/internal/logic"
	"go-svc/apps/inventory-rpc/internal/svc"
	"go-svc/apps/inventory-rpc/inventory"
)

type InventoryRpcServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryRpcServer
}

func NewInventoryRpcServer(svcCtx *svc.ServiceContext) *InventoryRpcServer {
	return &InventoryRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *InventoryRpcServer) SetStock(ctx context.Context, in *inventory.SetStockRequest) (*inventory.SetStockResponse, error) {
	l := logic.NewSetStockLogic(ctx, s.svcCtx)
	return l.SetStock(in)
}

func (s *InventoryRpcServer) GetStock(ctx context.Context, in *inventory.GetStockRequest) (*inventory.GetStockResponse, error) {
	l := logic.NewGetStockLogic(ctx, s.svcCtx)
	return l.GetStock(in)
}

func (s *InventoryRpcServer) DeductStock(ctx context.Context, in *inventory.DeductStockRequest) (*inventory.DeductStockResponse, error) {
	l := logic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}
