// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: apps/inventory-rpc/inventory.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryRpc_SetStock_FullMethodName    = "/inventory.InventoryRpc/SetStock"
	InventoryRpc_GetStock_FullMethodName    = "/inventory.InventoryRpc/GetStock"
	InventoryRpc_DeductStock_FullMethodName = "/inventory.InventoryRpc/DeductStock"
)

// InventoryRpcClient is the client API for InventoryRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryRpcClient interface {
	SetStock(ctx context.Context, in *SetStockRequest, opts ...grpc.CallOption) (*SetStockResponse, error)
	GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error)
	DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*DeductStockResponse, error)
}

type inventoryRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryRpcClient(cc grpc.ClientConnInterface) InventoryRpcClient {
	return &inventoryRpcClient{cc}
}

func (c *inventoryRpcClient) SetStock(ctx context.Context, in *SetStockRequest, opts ...grpc.CallOption) (*SetStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStockResponse)
	err := c.cc.Invoke(ctx, InventoryRpc_SetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryRpcClient) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockResponse)
	err := c.cc.Invoke(ctx, InventoryRpc_GetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryRpcClient) DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*DeductStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductStockResponse)
	err := c.cc.Invoke(ctx, InventoryRpc_DeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryRpcServer is the server API for InventoryRpc service.
// All implementations must embed UnimplementedInventoryRpcServer
// for forward compatibility.
type InventoryRpcServer interface {
	SetStock(context.Context, *SetStockRequest) (*SetStockResponse, error)
	GetStock(context.Context, *GetStockRequest) (*GetStockResponse, error)
	DeductStock(context.Context, *DeductStockRequest) (*DeductStockResponse, error)
	mustEmbedUnimplementedInventoryRpcServer()
}

// UnimplementedInventoryRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryRpcServer struct{}

func (UnimplementedInventoryRpcServer) SetStock(context.Context, *SetStockRequest) (*SetStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStock not implemented")
}
func (UnimplementedInventoryRpcServer) GetStock(context.Context, *GetStockRequest) (*GetStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedInventoryRpcServer) DeductStock(context.Context, *DeductStockRequest) (*DeductStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductStock not implemented")
}
func (UnimplementedInventoryRpcServer) mustEmbedUnimplementedInventoryRpcServer() {}
func (UnimplementedInventoryRpcServer) testEmbeddedByValue()                      {}

// UnsafeInventoryRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryRpcServer will
// result in compilation errors.
type UnsafeInventoryRpcServer interface {
	mustEmbedUnimplementedInventoryRpcServer()
}

func RegisterInventoryRpcServer(s grpc.ServiceRegistrar, srv InventoryRpcServer) {
	// If the following call panics, it indicates UnimplementedInventoryRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryRpc_ServiceDesc, srv)
}

func _InventoryRpc_SetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).SetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_SetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).SetStock(ctx, req.(*SetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryRpc_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).GetStock(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryRpc_DeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).DeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_DeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).DeductStock(ctx, req.(*DeductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryRpc_ServiceDesc is the grpc.ServiceDesc for InventoryRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.InventoryRpc",
	HandlerType: (*InventoryRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetStock",
			Handler:    _InventoryRpc_SetStock_Handler,
		},
		{
			MethodName: "GetStock",
			Handler:    _InventoryRpc_GetStock_Handler,
		},
		{
			MethodName: "DeductStock",
			Handler:    _InventoryRpc_DeductStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/inventory-rpc/inventory.proto",
}
