// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: apps/inventory-rpc/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inventories struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventories) Reset() {
	*x = Inventories{}
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventories) ProtoMessage() {}

func (x *Inventories) ProtoReflect() protoreflect.Message {
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventories.ProtoReflect.Descriptor instead.
func (*Inventories) Descriptor() ([]byte, []int) {
	return file_apps_inventory_rpc_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Inventories) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Inventories) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type SetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStockRequest) Reset() {
	*x = SetStockRequest{}
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStockRequest) ProtoMessage() {}

func (x *SetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStockRequest.ProtoReflect.Descriptor instead.
func (*SetStockRequest) Descriptor() ([]byte, []int) {
	return file_apps_inventory_rpc_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *SetStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SetStockRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type SetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStockResponse) Reset() {
	*x = SetStockResponse{}
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStockResponse) ProtoMessage() {}

func (x *SetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStockResponse.ProtoReflect.Descriptor instead.
func (*SetStockResponse) Descriptor() ([]byte, []int) {
	return file_apps_inventory_rpc_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *SetStockResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SetStockResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_apps_inventory_rpc_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_apps_inventory_rpc_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetStockResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetStockResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type DeductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockRequest) Reset() {
	*x = DeductStockRequest{}
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockRequest) ProtoMessage() {}

func (x *DeductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockRequest.ProtoReflect.Descriptor instead.
func (*DeductStockRequest) Descriptor() ([]byte, []int) {
	return file_apps_inventory_rpc_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *DeductStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductStockRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockResponse) Reset() {
	*x = DeductStockResponse{}
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResponse) ProtoMessage() {}

func (x *DeductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_inventory_rpc_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResponse.ProtoReflect.Descriptor instead.
func (*DeductStockResponse) Descriptor() ([]byte, []int) {
	return file_apps_inventory_rpc_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *DeductStockResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductStockResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_apps_inventory_rpc_inventory_proto protoreflect.FileDescriptor

const file_apps_inventory_rpc_inventory_proto_rawDesc = "" +
	"\n" +
	"\"apps/inventory-rpc/inventory.proto\x12\tinventory\"B\n" +
	"\vInventories\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"F\n" +
	"\x0fSetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"G\n" +
	"\x10SetStockResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"0\n" +
	"\x0fGetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"G\n" +
	"\x10GetStockResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"O\n" +
	"\x12DeductStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"J\n" +
	"\x13DeductStockResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock2\xe6\x01\n" +
	"\fInventoryRpc\x12C\n" +
	"\bSetStock\x12\x1a.inventory.SetStockRequest\x1a\x1b.inventory.SetStockResponse\x12C\n" +
	"\bGetStock\x12\x1a.inventory.GetStockRequest\x1a\x1b.inventory.GetStockResponse\x12L\n" +
	"\vDeductStock\x12\x1d.inventory.DeductStockRequest\x1a\x1e.inventory.DeductStockResponseB\rZ\v./inventoryb\x06proto3"

var (
	file_apps_inventory_rpc_inventory_proto_rawDescOnce sync.Once
	file_apps_inventory_rpc_inventory_proto_rawDescData []byte
)

func file_apps_inventory_rpc_inventory_proto_rawDescGZIP() []byte {
	file_apps_inventory_rpc_inventory_proto_rawDescOnce.Do(func() {
		file_apps_inventory_rpc_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_inventory_rpc_inventory_proto_rawDesc), len(file_apps_inventory_rpc_inventory_proto_rawDesc)))
	})
	return file_apps_inventory_rpc_inventory_proto_rawDescData
}

var file_apps_inventory_rpc_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_apps_inventory_rpc_inventory_proto_goTypes = []any{
	(*Inventories)(nil),         // 0: inventory.Inventories
	(*SetStockRequest)(nil),     // 1: inventory.SetStockRequest
	(*SetStockResponse)(nil),    // 2: inventory.SetStockResponse
	(*GetStockRequest)(nil),     // 3: inventory.GetStockRequest
	(*GetStockResponse)(nil),    // 4: inventory.GetStockResponse
	(*DeductStockRequest)(nil),  // 5: inventory.DeductStockRequest
	(*DeductStockResponse)(nil), // 6: inventory.DeductStockResponse
}
var file_apps_inventory_rpc_inventory_proto_depIdxs = []int32{
	1, // 0: inventory.InventoryRpc.SetStock:input_type -> inventory.SetStockRequest
	3, // 1: inventory.InventoryRpc.GetStock:input_type -> inventory.GetStockRequest
	5, // 2: inventory.InventoryRpc.DeductStock:input_type -> inventory.DeductStockRequest
	2, // 3: inventory.InventoryRpc.SetStock:output_type -> inventory.SetStockResponse
	4, // 4: inventory.InventoryRpc.GetStock:output_type -> inventory.GetStockResponse
	6, // 5: inventory.InventoryRpc.DeductStock:output_type -> inventory.DeductStockResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_inventory_rpc_inventory_proto_init() }
func file_apps_inventory_rpc_inventory_proto_init() {
	if File_apps_inventory_rpc_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_inventory_rpc_inventory_proto_rawDesc), len(file_apps_inventory_rpc_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_inventory_rpc_inventory_proto_goTypes,
		DependencyIndexes: file_apps_inventory_rpc_inventory_proto_depIdxs,
		MessageInfos:      file_apps_inventory_rpc_inventory_proto_msgTypes,
	}.Build()
	File_apps_inventory_rpc_inventory_proto = out.File
	file_apps_inventory_rpc_inventory_proto_goTypes = nil
	file_apps_inventory_rpc_inventory_proto_depIdxs = nil
}
