// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetUserReq struct {
	ID int64 `path:"id"`
}

type GetUserResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

type HealthzResp struct {
	Status string `json:"status"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	ID int64 `json:"id"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}
