// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: apps/user-rpc/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRpc_GetUser_FullMethodName                     = "/user.UserRpc/GetUser"
	UserRpc_GetOrCreateByKratosIdentity_FullMethodName = "/user.UserRpc/GetOrCreateByKratosIdentity"
	UserRpc_GetByKratosIdentity_FullMethodName         = "/user.UserRpc/GetByKratosIdentity"
)

// UserRpcClient is the client API for UserRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRpcClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// Phase 9: Kratos identity ↔ local user mapping.
	GetOrCreateByKratosIdentity(ctx context.Context, in *GetOrCreateByKratosIdentityRequest, opts ...grpc.CallOption) (*GetOrCreateByKratosIdentityResponse, error)
	GetByKratosIdentity(ctx context.Context, in *GetByKratosIdentityRequest, opts ...grpc.CallOption) (*GetByKratosIdentityResponse, error)
}

type userRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcClient(cc grpc.ClientConnInterface) UserRpcClient {
	return &userRpcClient{cc}
}

func (c *userRpcClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, UserRpc_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetOrCreateByKratosIdentity(ctx context.Context, in *GetOrCreateByKratosIdentityRequest, opts ...grpc.CallOption) (*GetOrCreateByKratosIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrCreateByKratosIdentityResponse)
	err := c.cc.Invoke(ctx, UserRpc_GetOrCreateByKratosIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetByKratosIdentity(ctx context.Context, in *GetByKratosIdentityRequest, opts ...grpc.CallOption) (*GetByKratosIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByKratosIdentityResponse)
	err := c.cc.Invoke(ctx, UserRpc_GetByKratosIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServer is the server API for UserRpc service.
// All implementations must embed UnimplementedUserRpcServer
// for forward compatibility.
type UserRpcServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// Phase 9: Kratos identity ↔ local user mapping.
	GetOrCreateByKratosIdentity(context.Context, *GetOrCreateByKratosIdentityRequest) (*GetOrCreateByKratosIdentityResponse, error)
	GetByKratosIdentity(context.Context, *GetByKratosIdentityRequest) (*GetByKratosIdentityResponse, error)
	mustEmbedUnimplementedUserRpcServer()
}

// UnimplementedUserRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRpcServer struct{}

func (UnimplementedUserRpcServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserRpcServer) GetOrCreateByKratosIdentity(context.Context, *GetOrCreateByKratosIdentityRequest) (*GetOrCreateByKratosIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrCreateByKratosIdentity not implemented")
}
func (UnimplementedUserRpcServer) GetByKratosIdentity(context.Context, *GetByKratosIdentityRequest) (*GetByKratosIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByKratosIdentity not implemented")
}
func (UnimplementedUserRpcServer) mustEmbedUnimplementedUserRpcServer() {}
func (UnimplementedUserRpcServer) testEmbeddedByValue()                 {}

// UnsafeUserRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRpcServer will
// result in compilation errors.
type UnsafeUserRpcServer interface {
	mustEmbedUnimplementedUserRpcServer()
}

func RegisterUserRpcServer(s grpc.ServiceRegistrar, srv UserRpcServer) {
	// If the following call panics, it indicates UnimplementedUserRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRpc_ServiceDesc, srv)
}

func _UserRpc_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetOrCreateByKratosIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateByKratosIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetOrCreateByKratosIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetOrCreateByKratosIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetOrCreateByKratosIdentity(ctx, req.(*GetOrCreateByKratosIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetByKratosIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByKratosIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetByKratosIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetByKratosIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetByKratosIdentity(ctx, req.(*GetByKratosIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRpc_ServiceDesc is the grpc.ServiceDesc for UserRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserRpc",
	HandlerType: (*UserRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserRpc_GetUser_Handler,
		},
		{
			MethodName: "GetOrCreateByKratosIdentity",
			Handler:    _UserRpc_GetOrCreateByKratosIdentity_Handler,
		},
		{
			MethodName: "GetByKratosIdentity",
			Handler:    _UserRpc_GetByKratosIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/user-rpc/user.proto",
}
