// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: apps/user-rpc/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetOrCreateByKratosIdentityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KratosIdentityId string                 `protobuf:"bytes,1,opt,name=kratos_identity_id,json=kratosIdentityId,proto3" json:"kratos_identity_id,omitempty"`
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrCreateByKratosIdentityRequest) Reset() {
	*x = GetOrCreateByKratosIdentityRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateByKratosIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateByKratosIdentityRequest) ProtoMessage() {}

func (x *GetOrCreateByKratosIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateByKratosIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateByKratosIdentityRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrCreateByKratosIdentityRequest) GetKratosIdentityId() string {
	if x != nil {
		return x.KratosIdentityId
	}
	return ""
}

func (x *GetOrCreateByKratosIdentityRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetOrCreateByKratosIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateByKratosIdentityResponse) Reset() {
	*x = GetOrCreateByKratosIdentityResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateByKratosIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateByKratosIdentityResponse) ProtoMessage() {}

func (x *GetOrCreateByKratosIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateByKratosIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateByKratosIdentityResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrCreateByKratosIdentityResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrCreateByKratosIdentityResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetByKratosIdentityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KratosIdentityId string                 `protobuf:"bytes,1,opt,name=kratos_identity_id,json=kratosIdentityId,proto3" json:"kratos_identity_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetByKratosIdentityRequest) Reset() {
	*x = GetByKratosIdentityRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByKratosIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByKratosIdentityRequest) ProtoMessage() {}

func (x *GetByKratosIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByKratosIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetByKratosIdentityRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetByKratosIdentityRequest) GetKratosIdentityId() string {
	if x != nil {
		return x.KratosIdentityId
	}
	return ""
}

type GetByKratosIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByKratosIdentityResponse) Reset() {
	*x = GetByKratosIdentityResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByKratosIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByKratosIdentityResponse) ProtoMessage() {}

func (x *GetByKratosIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByKratosIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetByKratosIdentityResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetByKratosIdentityResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetByKratosIdentityResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_apps_user_rpc_user_proto protoreflect.FileDescriptor

const file_apps_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x18apps/user-rpc/user.proto\x12\x04user\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"n\n" +
	"\"GetOrCreateByKratosIdentityRequest\x12,\n" +
	"\x12kratos_identity_id\x18\x01 \x01(\tR\x10kratosIdentityId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"Q\n" +
	"#GetOrCreateByKratosIdentityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"J\n" +
	"\x1aGetByKratosIdentityRequest\x12,\n" +
	"\x12kratos_identity_id\x18\x01 \x01(\tR\x10kratosIdentityId\"I\n" +
	"\x1bGetByKratosIdentityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername2\x91\x02\n" +
	"\aUserRpc\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12r\n" +
	"\x1bGetOrCreateByKratosIdentity\x12(.user.GetOrCreateByKratosIdentityRequest\x1a).user.GetOrCreateByKratosIdentityResponse\x12Z\n" +
	"\x13GetByKratosIdentity\x12 .user.GetByKratosIdentityRequest\x1a!.user.GetByKratosIdentityResponseB\bZ\x06./userb\x06proto3"

var (
	file_apps_user_rpc_user_proto_rawDescOnce sync.Once
	file_apps_user_rpc_user_proto_rawDescData []byte
)

func file_apps_user_rpc_user_proto_rawDescGZIP() []byte {
	file_apps_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_apps_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_user_rpc_user_proto_rawDesc), len(file_apps_user_rpc_user_proto_rawDesc)))
	})
	return file_apps_user_rpc_user_proto_rawDescData
}

var file_apps_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apps_user_rpc_user_proto_goTypes = []any{
	(*GetUserRequest)(nil),                      // 0: user.GetUserRequest
	(*GetUserResponse)(nil),                     // 1: user.GetUserResponse
	(*GetOrCreateByKratosIdentityRequest)(nil),  // 2: user.GetOrCreateByKratosIdentityRequest
	(*GetOrCreateByKratosIdentityResponse)(nil), // 3: user.GetOrCreateByKratosIdentityResponse
	(*GetByKratosIdentityRequest)(nil),          // 4: user.GetByKratosIdentityRequest
	(*GetByKratosIdentityResponse)(nil),         // 5: user.GetByKratosIdentityResponse
}
var file_apps_user_rpc_user_proto_depIdxs = []int32{
	0, // 0: user.UserRpc.GetUser:input_type -> user.GetUserRequest
	2, // 1: user.UserRpc.GetOrCreateByKratosIdentity:input_type -> user.GetOrCreateByKratosIdentityRequest
	4, // 2: user.UserRpc.GetByKratosIdentity:input_type -> user.GetByKratosIdentityRequest
	1, // 3: user.UserRpc.GetUser:output_type -> user.GetUserResponse
	3, // 4: user.UserRpc.GetOrCreateByKratosIdentity:output_type -> user.GetOrCreateByKratosIdentityResponse
	5, // 5: user.UserRpc.GetByKratosIdentity:output_type -> user.GetByKratosIdentityResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_user_rpc_user_proto_init() }
func file_apps_user_rpc_user_proto_init() {
	if File_apps_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_user_rpc_user_proto_rawDesc), len(file_apps_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_apps_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_apps_user_rpc_user_proto_msgTypes,
	}.Build()
	File_apps_user_rpc_user_proto = out.File
	file_apps_user_rpc_user_proto_goTypes = nil
	file_apps_user_rpc_user_proto_depIdxs = nil
}
