// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package server

import (
	"context"

	"go-svc/apps/product-rpc/internal/logic"
	"go-svc/apps/product-rpc/internal/svc"
	"go-svc/apps/product-rpc/product"
)

type ProductRpcServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductRpcServer
}

func NewProductRpcServer(svcCtx *svc.ServiceContext) *ProductRpcServer {
	return &ProductRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductRpcServer) CreateProduct(ctx context.Context, in *product.CreateProductRequest) (*product.CreateProductResponse, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

func (s *ProductRpcServer) GetProduct(ctx context.Context, in *product.GetProductRequest) (*product.GetProductResponse, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductRpcServer) ListProducts(ctx context.Context, in *product.ListProductsRequest) (*product.ListProductsResponse, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

func (s *ProductRpcServer) SetProductStatus(ctx context.Context, in *product.SetProductStatusRequest) (*product.SetProductStatusResponse, error) {
	l := logic.NewSetProductStatusLogic(ctx, s.svcCtx)
	return l.SetProductStatus(in)
}
