// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"go-svc/apps/user-rpc/internal/logic"
	"go-svc/apps/user-rpc/internal/svc"
	"go-svc/apps/user-rpc/user"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) GetUser(ctx context.Context, in *user.GetUserRequest) (*user.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// Phase 9: Kratos identity ↔ local user mapping.
func (s *UserRpcServer) GetOrCreateByKratosIdentity(ctx context.Context, in *user.GetOrCreateByKratosIdentityRequest) (*user.GetOrCreateByKratosIdentityResponse, error) {
	l := logic.NewGetOrCreateByKratosIdentityLogic(ctx, s.svcCtx)
	return l.GetOrCreateByKratosIdentity(in)
}

func (s *UserRpcServer) GetByKratosIdentity(ctx context.Context, in *user.GetByKratosIdentityRequest) (*user.GetByKratosIdentityResponse, error) {
	l := logic.NewGetByKratosIdentityLogic(ctx, s.svcCtx)
	return l.GetByKratosIdentity(in)
}
