syntax = "proto3";

package inventory;

option go_package = "./inventory";

message Inventories {
    int64 product_id = 1;
    int64 stock      = 2;
}

message SetStockRequest {
    int64 product_id = 1;
    int64 stock      = 2;
}

message SetStockResponse {
    int64 product_id = 1;
    int64 stock      = 2;
}

message GetStockRequest {
    int64 product_id = 1;
}

message GetStockResponse {
    int64 product_id = 1;
    int64 stock      = 2;
}

message DeductStockRequest {
    int64 product_id = 1;
    int64 quantity   = 2;
}

message DeductStockResponse {
    int64 product_id = 1;
    int64 stock      = 2;
}

service InventoryRpc {
    rpc SetStock(SetStockRequest) returns (SetStockResponse);
    rpc GetStock(GetStockRequest) returns (GetStockResponse);
    rpc DeductStock(DeductStockRequest) returns (DeductStockResponse);
}
