// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package productrpc

import (
	"context"

	"go-svc/apps/product-rpc/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateProductRequest     = product.CreateProductRequest
	CreateProductResponse    = product.CreateProductResponse
	GetProductRequest        = product.GetProductRequest
	GetProductResponse       = product.GetProductResponse
	ListProductsRequest      = product.ListProductsRequest
	ListProductsResponse     = product.ListProductsResponse
	SetProductStatusRequest  = product.SetProductStatusRequest
	SetProductStatusResponse = product.SetProductStatusResponse

	ProductRpc interface {
		CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
		GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
		ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
		SetProductStatus(ctx context.Context, in *SetProductStatusRequest, opts ...grpc.CallOption) (*SetProductStatusResponse, error)
	}

	defaultProductRpc struct {
		cli zrpc.Client
	}
)

func NewProductRpc(cli zrpc.Client) ProductRpc {
	return &defaultProductRpc{
		cli: cli,
	}
}

func (m *defaultProductRpc) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	client := product.NewProductRpcClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

func (m *defaultProductRpc) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	client := product.NewProductRpcClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

func (m *defaultProductRpc) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	client := product.NewProductRpcClient(m.cli.Conn())
	return client.ListProducts(ctx, in, opts...)
}

func (m *defaultProductRpc) SetProductStatus(ctx context.Context, in *SetProductStatusRequest, opts ...grpc.CallOption) (*SetProductStatusResponse, error) {
	client := product.NewProductRpcClient(m.cli.Conn())
	return client.SetProductStatus(ctx, in, opts...)
}
