global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "go-svc"
    metrics_path: /metrics
    static_configs:
      - targets:
          - gateway-api:6060
          - user-rpc:6060
          - product-rpc:6060
          - inventory-rpc:6060
          - order-rpc:6060
