// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: inventory.proto

package inventoryrpc

import (
	"context"

	"go-svc/apps/inventory-rpc/inventory"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductStockRequest  = inventory.DeductStockRequest
	DeductStockResponse = inventory.DeductStockResponse
	GetStockRequest     = inventory.GetStockRequest
	GetStockResponse    = inventory.GetStockResponse
	Inventories         = inventory.Inventories
	SetStockRequest     = inventory.SetStockRequest
	SetStockResponse    = inventory.SetStockResponse

	InventoryRpc interface {
		SetStock(ctx context.Context, in *SetStockRequest, opts ...grpc.CallOption) (*SetStockResponse, error)
		GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error)
		DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*DeductStockResponse, error)
	}

	defaultInventoryRpc struct {
		cli zrpc.Client
	}
)

func NewInventoryRpc(cli zrpc.Client) InventoryRpc {
	return &defaultInventoryRpc{
		cli: cli,
	}
}

func (m *defaultInventoryRpc) SetStock(ctx context.Context, in *SetStockRequest, opts ...grpc.CallOption) (*SetStockResponse, error) {
	client := inventory.NewInventoryRpcClient(m.cli.Conn())
	return client.SetStock(ctx, in, opts...)
}

func (m *defaultInventoryRpc) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error) {
	client := inventory.NewInventoryRpcClient(m.cli.Conn())
	return client.GetStock(ctx, in, opts...)
}

func (m *defaultInventoryRpc) DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*DeductStockResponse, error) {
	client := inventory.NewInventoryRpcClient(m.cli.Conn())
	return client.DeductStock(ctx, in, opts...)
}
