// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package server

import (
	"context"

	"go-svc/apps/order-rpc/internal/logic"
	"go-svc/apps/order-rpc/internal/svc"
	"go-svc/apps/order-rpc/order"
)

type OrderRpcServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderRpcServer
}

func NewOrderRpcServer(svcCtx *svc.ServiceContext) *OrderRpcServer {
	return &OrderRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderRpcServer) CreateOrder(ctx context.Context, in *order.CreateOrderRequest) (*order.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderRpcServer) GetOrder(ctx context.Context, in *order.GetOrderRequest) (*order.GetOrderResponse, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *OrderRpcServer) ListUserOrders(ctx context.Context, in *order.ListUserOrdersRequest) (*order.ListUserOrdersResponse, error) {
	l := logic.NewListUserOrdersLogic(ctx, s.svcCtx)
	return l.ListUserOrders(in)
}
